# Generated by Django 3.2.3 on 2021-05-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_title_article_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
